## Aula 01

@baseUrl = http://127.0.0.1:8098

### Países
GET {{baseUrl}}/paises
Accept: application/json

### Senegal 
GET {{baseUrl}}/paises/senegal
Accept: application/json

### Mônaco
GET {{baseUrl}}/paises/monaco/moeda
Accept: application/json


### Australia
GET {{baseUrl}}/paises/australia/idioma
Accept: application/json

### Africa
GET {{baseUrl}}/africa/independentes
Accept: application/json

